#
# Copyright (C) 2018 Amarula Solutions
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-$(CONFIG_RESET_SUN4I_A10) += reset_a10.o
obj-$(CONFIG_RESET_SUN8I_H3) += reset_h3.o
obj-$(CONFIG_RESET_SUN50I_A64) += reset_a64.o
